Repository smithmicro/mapbox-gl-circle, pull requests merged in 2022-10, with the labels that each got.

#94 Replace Jenkins CI/CD with GitHub Actions CI/CD + Modernizations
  .editorconfig
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/lint-and-build.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/publish-release.yml
  .gitignore
  .travis.yml
  Jenkinsfile
  README.md
  package-lock.json
  package.json
  prepare-release.sh
Labels: enhancement

#98 Finding GHP Rejects Un-Scoped NPM :package: (#93)
  .github/workflows/publish-prerelease.yml
  .github/workflows/publish-release.yml
  package-lock.json
  package.json
Labels: bug

#84 Move optionalDependencies to devDependencies
  Dockerfile
  README.md
  example/index.js
  package-lock.json
  package.json
Labels: dependencies
